### ISSUE TITLE
How to make Image inside GestureView Zoomable?

### ISSUE THREAD

**Issue by radiegtya** [kiddkai/react-native-gestures#15]

**Comment by sscaff1** [comment]
Look at my pull request #13. You should be able to specify a prop called type = "image" and then use an image with a source attribute.

**Comment by radiegtya** [comment]
its not working using this code

``` javascript
        <GestureView
          style={{position: "absolute", width: 300, height: 300, top: 50, left: 0, right: 0, bottom: 0}}
          gestures={[pinch]}
          type="image"
          toStyle={(layout) => {
            return {
              top: layout.y,
              left: layout.x,
              width: layout.width,
              height: layout.height,
              transform: [{rotate: `${layout.rotate}deg`}]
            }
          }}
          onError={console.error.bind(console)}
          source={{ uri: uri}}>
</GestureView>
```

I have adding the source and type, but still not working. any thought about this? Thanks @sscaff1

**Comment by radiegtya** [comment]
Fixed! the problem was with the npm itself is not the latest version react-native-gestures != master.

so I made my own package using this latest git master for quick fix:

```
https://www.npmjs.com/package/react-native-gesture
```

Thanks to the author & @sscaff1

**Comment by sscaff1** [comment]
Glad you got it resolved!
