### ISSUE TITLE
Using the component on multiple pages

### ISSUE THREAD

**Issue by 4ian** [kiddkai/react-native-gestures#21]
Hi there,

We've been using the GestureView component successfully, but since we've updated our app to React Native 0.25, it seems that I can't use the component more than once.
The first page showing it is working properly. If I go to another page (so that the component is unmounted) and then go back to the one showing the GesturesView, the gestures are not working.

I've tried to dig a bit in the code, and found a few things: for example, `gestureDefs` is mutated each time a GestureView component is mounted, so that it keeps growing... That's strange because each time `componentWillMount` is called, I guess that the number of gestures that are observed should be the same.

Any idea about this problem?

**Comment by jtewright** [comment]
Concur with 4ian. I've found that as soon as GestureView is unmounted once, the gestures won't work again. Nothing errors, you just can't pinch / drag. I'm using it on one page: navigating back unmounts, going into the page again the gestures don't work.

**Comment by reallistic** [comment]
I was able to track down the issue to right here:
https://github.com/kiddkai/react-native-gestures/blob/147c085/src/mixins/events.js#L14

When a new instance comes to play, the old (now invalid) `Rx.Subject` is still being used.
By doing the following, I was able to get this to work:

```
-- evs.forEach((ev) => streams[ev].onCompleted())
++ evs.forEach((ev) => {
++     var rv = streams[ev].onCompleted();
++     streams[ev] = new Rx.Subject();
++     return rv;
++ });
```

@kiddkai Do you see any negative side effects of this? I imagine its not an ideal fix, I would imagine the `streams` could be populated in `componentWillMount` (although when I tried that I got a weird binding error). I'm more than happy to submit a PR if you think this is a valid solution :).

**Comment by reallistic** [comment]
After further thought, i've realized that code shouldn't have ill effects. PR #23 has been submitted.
