### ISSUE TITLE
It is support android?

### ISSUE THREAD

**Issue by NemSothea** [kiddkai/react-native-gestures#31]

**Comment by assertchris** [comment]
It appears to, in #30. Since that uses much of the same PanResponder code as before, I believe to should work there too. I was having issues with certain style properties on an Image, but text works as expected.

**Comment by assertchris** [comment]
![android](https://user-images.githubusercontent.com/200609/30118826-4c6881e2-9324-11e7-9b0c-0640d399ce60.gif)
